#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : nbformat
Version  : 4.3.0
Release  : 5
URL      : http://pypi.debian.net/nbformat/nbformat-4.3.0.tar.gz
Source0  : http://pypi.debian.net/nbformat/nbformat-4.3.0.tar.gz
Summary  : The Jupyter Notebook format
Group    : Development/Tools
License  : BSD-3-Clause-Clear
Requires: nbformat-bin
Requires: nbformat-python
Requires: ipython_genutils
Requires: jsonschema
Requires: traitlets
BuildRequires : jsonschema
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
This package contains the base implementation of the Jupyter Notebook format,
            and Python APIs for working with notebooks.

%package bin
Summary: bin components for the nbformat package.
Group: Binaries

%description bin
bin components for the nbformat package.


%package python
Summary: python components for the nbformat package.
Group: Default

%description python
python components for the nbformat package.


%prep
%setup -q -n nbformat-4.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1503122146
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1503122146
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/jupyter-trust

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
